# Generated by Django 4.0.5 on 2022-07-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_alter_suppliermodel_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStockModel',
            fields=[
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel')),
            ],
        ),
    ]
