# Generated by Django 4.0.5 on 2023-02-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStockModel',
            fields=[
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('number', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=100)),
                ('engine_number', models.CharField(max_length=100)),
                ('purchase_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateField()),
                ('manufacturing_date', models.DateField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel')),
            ],
        ),
    ]
