# Generated by Django 4.0.5 on 2023-02-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_newstockmodel_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstockmodel',
            name='noc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='newstockmodel',
            name='noc_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseOnStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('DOCUMENT', 'Document'), ('MECHANIC', 'Mechanic'), ('SPARES', 'Spares'), ('OTHER', 'Other')], default='MECHANIC', max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.newstockmodel')),
            ],
        ),
    ]
