# Generated by Django 4.0.5 on 2023-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='available_quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
