# Generated by Django 4.0.5 on 2022-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
