# Generated by Django 4.0.5 on 2023-02-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_newstockmodel_manufacturing_date_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmodel',
            old_name='price',
            new_name='advance',
        ),
        migrations.RenameField(
            model_name='salesmodel',
            old_name='quantity',
            new_name='deal_price',
        ),
        migrations.RenameField(
            model_name='salesmodel',
            old_name='total_price',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='salesmodel',
            name='sku',
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchase.newstockmodel'),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='test_drive_taken',
            field=models.BooleanField(default=True),
        ),
    ]
